### ISSUE TITLE
这个仓库里面的代码，是原文作者发布的吗？

### ISSUE THREAD

**Issue by yang3kui** [qigemi/EDCircles#1]
hi，

我最近也读到了EDCircles这篇论文，然后在github上搜到了这个实现，我想问以下，这个代码是作者发布的。还是您这边自己按照原文写的？

**Comment by qigemi** [comment]
是我根据原文自己编写的，只是初步实现功能，没有优化。

**Comment by yang3kui** [comment]
昨天试了一下，圆的部分效果还不错，好像椭圆的部分还有Bug~~

**Comment by qigemi** [comment]
是的，椭圆好像是在方程拟合的地方有问题，时间比较久了，也没有再调试，不好意思。

**Comment by ZhiboRao** [comment]
我也希望能完整的实现EDcircles算法，不知道你们现在有没有新的进展。我的邮箱是raoxi36@163.com。我有些问题想像你们请教

**Comment by ZhiboRao** [comment]
你们好：
我测试了一下，我自己的图片。发现您的这部分代码漏检比较严重。但他们官方网站上的效果非常好。
我通过大量的测试，发现一下几个现象：
1、网站上提供的EDPF算法的DLL的效果，远不如网站的demo效果好；
2、您实现的EDCircles版本和网站上的效果也有比较大的差距，您认为该差距是哪个部分造成的。
如果您能为我提供一些帮助，不胜感谢。多谢
