### ISSUE TITLE
为什么每个方向有两个函数？

### ISSUE THREAD

**Issue by kli017** [qigemi/EDCircles#2]
仔细查看了下没发现有什么不同，请问两个函数作用不一样吗

**Comment by qigemi** [comment]
因为边缘点保存在链表里，我构建了一个双向链表，当从一个anchor分别向两头找边缘的时候我希望这两条边缘保存在同一个链表里，所以同一个方向有两个函数，一个是往链表的尾部插入点，一个是往头部插入点。
之前写这个程序的时候没有学过计算机相关的课，这个找边缘的过程或许用深度优先的遍历会好一些，我这个写的太乱了。

**Comment by kli017** [comment]
谢谢回复，能把算法复现出来已经很棒了，学习了

**Comment by watchmexiang** [comment]
您好 请问以下您的代码进行一次实验运行时间是多少啊 我用了一个640*480的图片进行了实验用了1秒多，请问下您的代码与原论文是否一致，原论文宣称需要20ms左右，打扰您了，谢谢

**Comment by watchmexiang** [comment]
您尝试实时了吗 我试了下不行

**Comment by qigemi** [comment]
这份代码确实不能实时，只能说算法和原文一样，原文作者应该做了很多优化吧。

**Comment by watchmexiang** [comment]
好的 谢谢您了 您能复现这个代码已经十分不容易了 我想找一个实时性强鲁棒性高的识别圆的算法

**Comment by jinyqjinyq** [comment]
您好，我使用这个代码进行原检测测试的时候，其检测效果并不能达到论文中所说的效果，我使用的是车载摄像头拍摄的圆形交通标志的图片，不知您测试的效果如何呢？

**Comment by qigemi** [comment]
我做的测试很少，比较正的圆可以检测出来，椭圆检测还有问题
